apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appofapps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: appofapps
spec:
  project: default
  source:
    repoURL: https://github.com/arimal199-org/argo-playground.git
    # targetRevision: HEAD
    targetRevision: new
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
